### ISSUE TITLE
Build Failure Macos 10.4 10.5 G4 PowerPC through Macports/PowerPC Ports

### ISSUE THREAD

**Issue by ForestExpertise** [iains/gcc-15-branch#3]
Hello,
I recently tried to compile gcc15 through Macports. I have attached the log of the build failure. I would appreciate any help as I am still pretty new to this and trying to keep ports alive on Tiger
Thank you!

[libgcc15.txt](https://github.com/user-attachments/files/22587409/libgcc15.txt)

**Comment by barracuda156** [comment]
@ForestExpertise It makes life easier if you quote the error in the post (and still attach the full log, of course).

```
:info:build make[3]: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build/powerpc-apple-darwin8/libgcc'
:info:build Makefile:902: no file name for `-include'
:info:build Makefile:1222: no file name for `-include'
:info:build # If this is the top-level multilib, build all the other
:info:build # multilibs.
:info:build ln -s /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/gthr-posix.h gthr-default.h
:info:build ln -s /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/config/rs6000/darwin-unwind.h md-unwind-support.h
:info:build ln -s /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/unwind-generic.h unwind.h
:info:build DEFINES='' HEADERS='/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/config/i386/darwin-lib.h' \
:info:build 	/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/mkheader.sh > tmp-libgcc_tm.h
:info:build /bin/sh /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/../move-if-change tmp-libgcc_tm.h libgcc_tm.h
:info:build echo timestamp > libgcc_tm.stamp
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build/./gcc/xgcc -B/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build/./gcc/ -B/opt/local/powerpc-apple-darwin8/bin/ -B/opt/local/powerpc-apple-darwin8/lib/ -isystem /opt/local/powerpc-apple-darwin8/include -isystem /opt/local/powerpc-apple-darwin8/sys-include   -fno-checking -g -O2 -pipe -Os -O2  -g -O2 -pipe -Os -DIN_GCC   -W -Wall -Wno-error=narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -mmacosx-version-min=10.4 -Wa,-force_cpusubtype_ALL -fno-common -mlong-double-128 -maltivec -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -mmacosx-version-min=10.4 -Wa,-force_cpusubtype_ALL -fno-common -mlong-double-128 -maltivec -I. -I. -I../.././gcc -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/. -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/../gcc -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/../include     -o unwind-dw2_s.o -MT unwind-dw2_s.o -MD -MP -MF unwind-dw2_s.dep -DSHARED -fexceptions -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/unwind-dw2.c
:info:build In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/unwind-dw2.c:38:
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/gcc-15.1.0/libgcc/unwind-dw2.h:25:10: fatal error: md-unwind-def.h: No such file or directory
:info:build    25 | #include "md-unwind-def.h"
:info:build       |          ^~~~~~~~~~~~~~~~~
:info:build compilation terminated.
:info:build make[3]: *** [unwind-dw2_s.o] Error 1
:info:build make[3]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build/powerpc-apple-darwin8/libgcc'
:info:build make[2]: *** [all-stage1-target-libgcc] Error 2
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build'
:info:build make[1]: *** [stage1-bubble] Error 2
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build'
:info:build make: *** [bootstrap-lean] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build'
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc15/libgcc15/work/build" && /usr/bin/make -w bootstrap-lean 
:info:build Exit code: 2
```

@iains I do not know for sure if the build works on 10.5–10.6 yet, since the last snapshot I built was from March 2025, and I still keep my ports at gcc14 by default. If related changes pre-date 15-20250323, then the failure is Tiger-specific.

P. S. Unlikely it matters, given the error here, but the build does not use `xtools`, `llas` or anything like that (MacPorts never used them, and I made `xtools` the default on 10.5+).

**Comment by barracuda156** [comment]
@glebm You may be interested to follow.

**Comment by barracuda156** [comment]
Looks like on 10.5 everything [builds](https://forums.macrumors.com/threads/ppcports-the-only-ports-you-ever-need-on-a-powerpc.2462897/page-4?post=34190028#post-34190028) fine, so the issue _is_ Tiger-specific.

**Comment by barracuda156** [comment]
Ticket on bugzilla: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=123976

**Comment by ForestExpertise** [comment]
> Ticket on bugzilla: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=123976

Thanks for posting this here to verify that this is a 32-bit issue, not a Tiger issue. I should fix the title of the issue now.

**Comment by barracuda156** [comment]
> Thanks for posting this here to verify that this is a 32-bit issue, not a Tiger issue. I should fix the title of the issue now.

It is not a 32-bit issue either, since this error does not happen on 10.6 ppc, which is of course only 32-bit on powerpc.

(I am not sure about 10.5 ppc64, since I did not build any gcc later than 14.3.0 there.)

**Comment by iains** [comment]
0. If you want to post a problem to be solved here, it needs to be reproducible **_outside_** the macports system; there is a lot of special magic sauce in that, and to fix problems upstream we need to separate the out.
 
1.  I no longer test on 10.4 (lack of viable h/w - trunk  build and test on a 500MHz G4 takes ≈ 1 week).

2. 10.4 has some considerable challenges for modern C++ .. I would expect that you'd need to update some tools and certainly the linker and assembler.

I do still test 10.5 regularly on x86 (like every few days), and I can say with certainly that 15.x-darwin releases have _definitely_ been bootstrapped and tested on it 

(I am hoping to get some replacement powerpc h/w soon, that will allow me to test there too)

**Comment by ForestExpertise** [comment]
> 0. If you want to post a problem to be solved here, it needs to be reproducible **_outside_** the macports system; there is a lot of special magic sauce in that, and to fix problems upstream we need to separate the out.
> 
>     1. I no longer test on 10.4 (lack of viable h/w - trunk  build and test on a 500MHz G4 takes ≈ 1 week).
> 
>     2. 10.4 has some considerable challenges for modern C++ .. I would expect that you'd need to update some tools and certainly the linker and assembler.
> 
> 
> I do still test 10.5 regularly on x86 (like every few days), and I can say with certainly that 15.x-darwin releases have _definitely_ been bootstrapped and tested on it
> 
> (I am hoping to get some replacement powerpc h/w soon, that will allow me to test there too)

Thanks for mentioning 0 - I am unsure this problem is reproducible outside of ports, so I will close the issue. If anyone needs a quick fix, making the symlink as described in the Macports ticket manually does work.



> > Thanks for posting this here to verify that this is a 32-bit issue, not a Tiger issue. I should fix the title of the issue now.
> 
> It is not a 32-bit issue either, since this error does not happen on 10.6 ppc, which is of course only 32-bit on powerpc.
> 
> (I am not sure about 10.5 ppc64, since I did not build any gcc later than 14.3.0 there.)

Perhaps I should say it is a G4 issue, to be more precise. We know this failure occurs in both Macports and PowerPC ports on G4s running Leopard and Tiger. Has anyone successfully built gcc16 or 15 on a G4 running Snow Leopard PowerPC? I know someone mentioned they had a failure building on a Powerbook G4 over on the Macrumors forum, but since they didn't post the log we have no way of knowing if they ran into the same issue described here and in the ticket.

**Comment by barracuda156** [comment]
> I am unsure this problem is reproducible outside of ports

@ForestExpertise It should not be too hard to try, since all dependencies of gcc can be built in-tree on 10.5. One only needs gcc10-bootstrap, which can be borrowed from ports (it exists pre-built for 10.5). Then just configure gcc to use that compiler. I.e. at least in case of 10.5/10.6 there is no need to build anything extra or depend on ports at runtime.
